services:
 db:
  image: postgres:14.1-alpine
  restart: always
  environment:
   - POSTGRES_PASSWORD=postgres
   - POSTGRES_USER=postgres
  ports:
   - "15432:5432"
  volumes:
   - db:/var/lib/postgresql/data
volumes:
 db:
  driver: local
